INSERT INTO districtos(id,nome,provincia_id) VALUES (14,'Ancuabe',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (15,'Balama',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (16,'Chiúre',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (17,'Ibo',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (18,'Macomia',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (19,'Mecúfi',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (20,'Meluco',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (21,'Metuge',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (22,'Mocímboa da Praia',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (23,'Montepuez',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (24,'Chimbonila',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (25,'Cuamba',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (26,'Lago',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (27,'Lichinga',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (28,'Angónia',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (29,'Cahora-Bassa',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (30,'Changara',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (31,'Tsangano',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (32,'Alto Molócuè',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (33,'Chinde',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (34,'Maganja da Costa',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (35,'Namarroi',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (36,'Funhalouro',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (37,'Govuro',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (38,'Inhambane',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (39,'Zavala',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (40,'Boane',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (41,'Magude',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (42,'Manhiça',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (43,'Matola',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (44,'Marracuene',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (45,'Matutuíne',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (46,'Moamba',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (47,'Namaacha',4);
INSERT INTO districtos(id,nome,provincia_id) VALUES (62,'Distrito Urbano de KaMpfumo',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (63,'Distrito Urbano de Nlhamankulu',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (64,'Distrito Urbano de KaMaxaquene',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (65,'Distrito Urbano de KaMavota',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (66,'Distrito Urbano de KaMubukwana',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (67,'Distrito Municipal de KaTembe',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (68,'Distrito Municipal de KaNyaka',3);
INSERT INTO districtos(id,nome,provincia_id) VALUES (69,'Bilene Macia',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (70,'Chibuto',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (71,'Chicualacuala',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (72,'Chigubo',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (73,'Chókwè',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (74,'Guijá',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (75,'Mabalane',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (76,'Manjacaze',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (77,'Massangena',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (78,'Massingir',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (79,'Xai-Xai',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (80,'Xai-Xai Cidade',5);
INSERT INTO districtos(id,nome,provincia_id) VALUES (95,'Homoíne',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (96,'Inharrime',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (97,'Inhassoro',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (98,'Jangamo',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (99,'Mabote',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (100,'Massinga',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (101,'Maxixe',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (102,'Morrumbene',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (103,'Panda',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (104,'Vilanculos',6);
INSERT INTO districtos(id,nome,provincia_id) VALUES (106,'Búzi',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (107,'Caia',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (108,'Chemba',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (109,'Cheringoma',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (110,'Chibabava',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (111,'Dondo',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (112,'Gorongosa',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (113,'Machanga',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (114,'Maringué',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (115,'Marromeu',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (116,'Muanza',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (117,'Nhamatanda',8);
INSERT INTO districtos(id,nome,provincia_id) VALUES (118,'Bárue',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (119,'Gondola',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (120,'Guro',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (121,'Machaze',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (122,'Macossa',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (123,'Mossurize',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (124,'Sussundenga',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (125,'Tambara',7);
INSERT INTO districtos(id,nome,provincia_id) VALUES (126,'Angoche',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (127,'Eráti',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (128,'Lalaua',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (129,'Malema',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (130,'Meconta',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (131,'Mecubúri',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (132,'Memba',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (133,'Mogincual',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (134,'Mogovolas',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (135,'Moma',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (136,'Monapo',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (137,'Mossuril',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (138,'Muecate',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (139,'Murrupula',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (140,'Nacala-a-Velha',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (141,'Nacarôa',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (142,'Nampula',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (143,'Ribaué',11);
INSERT INTO districtos(id,nome,provincia_id) VALUES (144,'GILE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (145,'CIDADE QUELIMANE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (146,'GURUE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (147,'ILE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (148,'INHASSUNGE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (149,'LUGELA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (150,'MILANGE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (151,'MOCUBA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (152,'MOPEIA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (153,'MORRUMBALA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (154,'NAMACURRA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (155,'NICOADALA',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (156,'PEBANE',9);
INSERT INTO districtos(id,nome,provincia_id) VALUES (157,NULL,10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (158,'CIDADE DE TETE',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (159,'CHIFUNDE',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (160,'CHIUTA',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (161,'MACANGA',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (162,'MAGOE',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (163,'MARAVIA',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (164,'MOATIZE',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (165,'MUTARARA',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (166,'ZUMBO',10);
INSERT INTO districtos(id,nome,provincia_id) VALUES (167,'Cidade de Lichinga',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (168,'Majune',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (169,'Mandimba',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (170,'Marrupa',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (171,'Maua',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (172,'Mavago',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (173,'Mecanhelas',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (174,'Mecula',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (175,'Metarica',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (176,'Meumbe',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (177,'N´gauma',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (178,'Nipepe',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (179,'Sanga',12);
INSERT INTO districtos(id,nome,provincia_id) VALUES (180,'CIDADE DE PEMBA',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (181,'MUEDA',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (182,'MUIDUMBE',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (183,'NAMUNO',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (184,'NANGADE',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (185,'PALMA',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (186,'PEMBA METUGE',13);
INSERT INTO districtos(id,nome,provincia_id) VALUES (187,'QUISSANGA',13);
