INSERT INTO provincias(id,nome) VALUES (3,'Maputo Cidade');
INSERT INTO provincias(id,nome) VALUES (4,'Maputo Província');
INSERT INTO provincias(id,nome) VALUES (5,'Gaza');
INSERT INTO provincias(id,nome) VALUES (6,'Inhambane');
INSERT INTO provincias(id,nome) VALUES (7,'Manica');
INSERT INTO provincias(id,nome) VALUES (8,'Sofala');
INSERT INTO provincias(id,nome) VALUES (9,'Zambézia');
INSERT INTO provincias(id,nome) VALUES (10,'Tete');
INSERT INTO provincias(id,nome) VALUES (11,'Nampula');
INSERT INTO provincias(id,nome) VALUES (12,'Niassa');
INSERT INTO provincias(id,nome) VALUES (13,'Cabo delgado');
